"""Create paints table

Revision ID: efc272891e25
Revises: 
Create Date: 2026-01-10 17:49:52.755658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc272891e25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('surface_type', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('finish_type', sa.String(length=50), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('line', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('interno', 'externo')", name='check_environment'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paints_id'), 'paints', ['id'], unique=False)
    op.create_index(op.f('ix_paints_line'), 'paints', ['line'], unique=False)
    op.create_index(op.f('ix_paints_name'), 'paints', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paints_name'), table_name='paints')
    op.drop_index(op.f('ix_paints_line'), table_name='paints')
    op.drop_index(op.f('ix_paints_id'), table_name='paints')
    op.drop_table('paints')
    # ### end Alembic commands ###
